
// This file has been generated by the GUI designer. Do not modify.
namespace OCTO4
{
	public partial class WidgetBuscarRemplazar
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action goUpAction;
		
		private global::Gtk.Action goDownAction;
		
		private global::Gtk.Action cancelAction;
		
		private global::Gtk.Action Action;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.HBox hbox16;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OCTO4.WidgetBuscarRemplazar
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.goUpAction = new global::Gtk.Action ("goUpAction", null, null, "gtk-go-up");
			w2.Add (this.goUpAction, null);
			this.goDownAction = new global::Gtk.Action ("goDownAction", null, null, "gtk-go-down");
			w2.Add (this.goDownAction, null);
			this.cancelAction = new global::Gtk.Action ("cancelAction", null, null, "gtk-cancel");
			w2.Add (this.cancelAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w2.Add (this.Action, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "OCTO4.WidgetBuscarRemplazar";
			// Container child OCTO4.WidgetBuscarRemplazar.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			this.hbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox16]));
			w3.Position = 1;
			this.vbox8.Add (this.hbox15);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox15]));
			w4.Position = 1;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
