
// This file has been generated by the GUI designer. Do not modify.
namespace OCTO4
{
	public partial class TextWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action goDownAction;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView codigo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OCTO4.TextWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.goDownAction = new global::Gtk.Action ("goDownAction", null, null, "gtk-go-down");
			w2.Add (this.goDownAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "OCTO4.TextWidget";
			// Container child OCTO4.TextWidget.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.codigo = new global::Gtk.TextView ();
			this.codigo.CanFocus = true;
			this.codigo.Name = "codigo";
			this.GtkScrolledWindow.Add (this.codigo);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
			w4.Position = 0;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w5.Position = 0;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.codigo.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnTextview2KeyReleaseEvent);
		}
	}
}
